{% set name = "xorg-libxres" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/xorg/lib/libxres/-/archive/libXres-{{ version }}/libxres-libXres-{{ version }}.tar.gz
  sha256: 651e5d131ebcd8dbe72eccc84f4fbfc754abc02fe825301db2f38102715be25b

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - libtool
    - gnuconfig  # [unix]
    - autoconf  # [unix]
    - automake  # [unix]
    - make  # [unix]
    - xorg-util-macros
  host:
    - xorg-util-macros
    - xorg-libx11
    - xorg-xorgproto
    - xorg-libxext
    - xorg-xextproto
  run:
    - xorg-libx11
    - xorg-libxext

test:
  commands:
    - test -e $PREFIX/lib/libXRes.so  # [linux]
    - test -e $PREFIX/lib/libXRes.dylib  # [osx]

about:
  home: https://gitlab.freedesktop.org/xorg/lib/libXRes
  summary: X-Resource extension client library
  description: |
    X-Resource is an extension that allows a client to query the X
    server about its usage of various resources.  It should not be confused
    with the X resource database access functions.
  license: MIT
  license_family: MIT
  license_file: COPYING
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libXRes

extra:
  recipe-maintainers:
    - erykoff
